"""Конфигурация"""
from .config import (
    ALLOWED_ORIGINS,
    SECRET_KEY,
    ACCESS_TOKEN_EXPIRE_MINUTES,
    DATABASE_URL,
    ENVIRONMENT,
    OPENROUTER_API_KEY,
    DEBUG,
    PORT,
    GOOGLE_ALLOWED_CLIENT_IDS,
    GOOGLE_CLIENT_ID,
    COOKIE_SECURE,
    COOKIE_SAMESITE,
)
