import { createContext, useContext, useState, type ReactNode } from "react";

type Lang = "ru" | "en";

const t = {
  // Sidebar & Nav
  "nav.learn": { ru: "Обучение", en: "Learn" },
  "nav.modes": { ru: "Режимы", en: "Modes" },
  "nav.more": { ru: "Ещё", en: "More" },
  "nav.home": { ru: "Главная", en: "Home" },
  "nav.freeConversation": { ru: "Свободный диалог", en: "Free Conversation" },
  "nav.vocabulary": { ru: "Словарь", en: "Vocabulary" },
  "nav.listeningLab": { ru: "Аудирование", en: "Listening Lab" },
  "nav.audioConversation": { ru: "Аудиоразговор", en: "Audio Conversation" },
  "nav.grammarQuest": { ru: "Грамматика", en: "Grammar Quest" },
  "nav.pronunciation": { ru: "Произношение", en: "Pronunciation" },
  "nav.writingMentor": { ru: "Письмо", en: "Writing Mentor" },
  "nav.settings": { ru: "Настройки", en: "Settings" },
  "nav.skillMap": { ru: "Карта навыков", en: "Skill Map" },
  "nav.menu": { ru: "Меню", en: "Menu" },
  "nav.library": { ru: "Библиотека", en: "Library" },
  "nav.chat": { ru: "Чат", en: "Chat" },
  "nav.chatHistory": { ru: "История чатов", en: "Chat history" },
  "nav.newChat": { ru: "Новый", en: "New" },
  "nav.stats": { ru: "Статистика", en: "Stats" },
  "newChat.voiceChat": { ru: "Голосовой чат", en: "Voice chat" },
  "newChat.regularChat": { ru: "Обычный чат", en: "Text chat" },
  "newChat.vocabulary": { ru: "Словарь", en: "Vocabulary" },
  "common.cancel": { ru: "Отмена", en: "Cancel" },
  "common.save": { ru: "Сохранить", en: "Save" },
  "nav.profile": { ru: "Профиль", en: "Profile" },

  // Home
  "home.greeting": { ru: "Привет, Алекс 👋", en: "Hi, Alex 👋" },
  "home.subtitle": { ru: "Готов продолжить обучение?", en: "Ready to continue learning?" },
  "home.streak": { ru: "Серия", en: "Streak" },
  "home.streakValue": { ru: "12 дней", en: "12 days" },
  "home.today": { ru: "Сегодня", en: "Today" },
  "home.todayValue": { ru: "13 мин", en: "13 min" },
  "home.words": { ru: "Слова", en: "Words" },
  "home.level": { ru: "Уровень", en: "Level" },
  "home.dailyGoal": { ru: "Дневная цель", en: "Daily goal" },
  "home.dailyGoalProgress": { ru: "13 / 20 мин", en: "13 / 20 min" },
  "home.continueConversation": { ru: "Продолжить диалог", en: "Continue conversation" },
  "home.continueDesc": { ru: "Роль: Повар · Уровень A2 · Осталось 4 мин", en: "Chef role · A2 level · 4 min left" },
  "home.modes": { ru: "Режимы", en: "Modes" },
  "home.startChat": { ru: "Начать чат", en: "Start chat" },
  "home.quickStart": { ru: "Быстрый старт", en: "Quick start" },
  "home.goalReached": { ru: "Цель достигнута!", en: "Goal reached!" },
  "home.weeklyActivity": { ru: "Активность за неделю", en: "Weekly activity" },
  "home.conversations": { ru: "Диалоги", en: "Conversations" },
  "home.totalMinutes": { ru: "Всего минут за неделю", en: "Total minutes this week" },
  "home.freeConvTitle": { ru: "Свободный диалог", en: "Free Conversation" },
  "home.freeConvDesc": { ru: "Выберите уровень и роль. Практикуйте реальные диалоги.", en: "Choose level & role. Practice real dialogues." },
  "home.vocabTitle": { ru: "Режим словаря", en: "Vocabulary Mode" },
  "home.vocabDesc": { ru: "Выучите 10 слов → Говорите с ИИ, используя их.", en: "Learn 10 words → Speak with AI using them." },
  "home.listenTitle": { ru: "Аудирование", en: "Listening Lab" },
  "home.listenDesc": { ru: "Видео + интерактивные субтитры.", en: "Video + interactive subtitles." },
  "home.audioTitle": { ru: "Аудиоразговор", en: "Audio Conversation" },
  "home.audioDesc": { ru: "Говорите вслух — ИИ слушает и отвечает голосом.", en: "Speak aloud — AI listens and responds with voice." },

  // Setup
  "setup.title": { ru: "Новый чат", en: "New chat" },
  "setup.subtitle": { ru: "Выберите настройки. Их можно будет изменить позже.", en: "Choose settings. You can change them later." },
  "setup.chatType": { ru: "Тип чата", en: "Chat type" },
  "setup.voiceChat": { ru: "Голосовой чат", en: "Voice chat" },
  "setup.voiceChatDesc": { ru: "Говорите вслух — ИИ слушает и отвечает голосом", en: "Speak aloud — AI listens and responds with voice" },
  "setup.textChat": { ru: "Обычный чат", en: "Text chat" },
  "setup.textChatDesc": { ru: "Текстовый диалог с ролями и ситуациями", en: "Text dialogue with roles and situations" },
  "setup.vocabChat": { ru: "Практика по словарю", en: "Vocabulary practice" },
  "setup.vocabChatDesc": { ru: "Используйте активные слова в диалоге с ИИ", en: "Use active vocabulary in dialogue with AI" },
  "setup.createChat": { ru: "Создать чат", en: "Create chat" },
  "setup.chatName": { ru: "Название чата", en: "Chat name" },
  "setup.chatNamePlaceholder": { ru: "Введите название...", en: "Enter chat name..." },
  "setup.chatAvatar": { ru: "Аватар чата", en: "Chat avatar" },
  "setup.level": { ru: "Уровень", en: "Level" },
  "setup.context": { ru: "Контекст", en: "Context" },
  "setup.contextNone": { ru: "Без контекста", en: "No context" },
  "setup.contextCustom": { ru: "С контекстом", en: "With context" },
  "setup.customContextPlaceholder": { ru: "Опишите тему или сценарий диалога...", en: "Describe the topic or dialogue scenario..." },
  "setup.situation": { ru: "Ситуация (необязательно)", en: "Situation (optional)" },
  "setup.situationPlaceholder": { ru: "напр. Заказ еды в ресторане", en: "e.g. Ordering food in a restaurant" },
  "setup.start": { ru: "Начать говорить →", en: "Start Speaking →" },
  "setup.chef": { ru: "Повар", en: "Chef" },
  "setup.tourist": { ru: "Турист", en: "Tourist" },
  "setup.shopAssistant": { ru: "Продавец", en: "Shop Assistant" },
  "setup.officeWorker": { ru: "Офисный работник", en: "Office Worker" },
  "setup.student": { ru: "Студент", en: "Student" },
  "setup.fitnessCoach": { ru: "Фитнес-тренер", en: "Fitness Coach" },
  "setup.doctor": { ru: "Врач", en: "Doctor" },
  "setup.hotelReceptionist": { ru: "Регистрация в отеле", en: "Hotel receptionist" },
  "setup.airportStaff": { ru: "Сотрудник аэропорта", en: "Airport staff" },
  "setup.interviewer": { ru: "Собеседующий", en: "Job interviewer" },
  "setup.waiter": { ru: "Официант", en: "Waiter" },
  "setup.barista": { ru: "Бариста", en: "Barista" },
  "setup.taxiDriver": { ru: "Таксист", en: "Taxi driver" },
  "setup.librarian": { ru: "Библиотекарь", en: "Librarian" },
  "setup.realtor": { ru: "Риелтор", en: "Real estate agent" },
  "setup.nurse": { ru: "Медсестра", en: "Nurse" },
  "setup.scenarioRestaurant": { ru: "Заказ еды в ресторане", en: "Ordering food at a restaurant" },
  "setup.scenarioHotel": { ru: "Регистрация в отеле", en: "Hotel check-in" },
  "setup.scenarioAirport": { ru: "В аэропорту: регистрация, багаж", en: "At the airport: check-in, baggage" },
  "setup.scenarioJobInterview": { ru: "Собеседование на работу", en: "Job interview" },
  "setup.scenarioShopping": { ru: "Покупка одежды в магазине", en: "Shopping for clothes" },
  "setup.scenarioDirections": { ru: "Спросить дорогу", en: "Asking for directions" },
  "setup.scenarioDoctor": { ru: "Приём у врача", en: "Doctor's appointment" },
  "setup.scenarioParty": { ru: "Светская беседа на вечеринке", en: "Small talk at a party" },
  "setup.scenarioComplaint": { ru: "Жалоба на сервис", en: "Complaining about service" },
  "setup.scenarioReservation": { ru: "Бронирование столика", en: "Making a table reservation" },
  "setup.scenarioPharmacy": { ru: "В аптеке: купить лекарство", en: "At the pharmacy: buying medicine" },
  "setup.scenarioBank": { ru: "В банке: открыть счёт", en: "At the bank: opening an account" },

  // Vocabulary
  "vocab.title": { ru: "Словарь", en: "Vocabulary" },
  "vocab.subtitle": { ru: "В ресторане · 8 слов", en: "At the Restaurant · 8 words" },
  "vocab.practice": { ru: "Практика с ИИ →", en: "Practice with AI →" },
  "vocab.addWord": { ru: "Добавить новое слово", en: "Add new word" },
  "vocab.wordPlaceholder": { ru: "Слово (англ. или рус.)", en: "Word (EN or RU)" },
  "vocab.getTranslation": { ru: "Получить перевод", en: "Get translation" },
  "vocab.addToDict": { ru: "Добавить в словарь", en: "Add to dictionary" },
  "vocab.translation": { ru: "Перевод", en: "Translation" },
  "vocab.phonetic": { ru: "Транскрипция", en: "Phonetic" },
  "vocab.examples": { ru: "Примеры", en: "Examples" },
  "vocab.loading": { ru: "Загрузка...", en: "Loading..." },
  "vocab.activeDict": { ru: "Активный словарь", en: "Active vocabulary" },
  "vocab.passiveDict": { ru: "Пассивный словарь", en: "Passive vocabulary" },
  "vocab.activeHint": { ru: "Участвуют в практике с ИИ. Перетащите в пассивный, чтобы убрать.", en: "Used in AI practice. Drag to passive to exclude." },
  "vocab.passiveHint": { ru: "Не участвуют в практике. Перетащите в активный, чтобы добавить.", en: "Not used in practice. Drag to active to include." },

  // Chat
  "chat.typeMessage": { ru: "Введите сообщение...", en: "Type your message..." },
  "chat.vocabPractice": { ru: "Практика словаря", en: "Vocabulary Practice" },
  "chat.activeWords": { ru: "🔤 Активные слова:", en: "🔤 Active words:" },
  "vocab.editDict": { ru: "Редактировать словарь", en: "Edit dictionary" },
  "vocab.openFullDict": { ru: "Открыть полный словарь", en: "Open full dictionary" },
  "chat.coachGreeting": { ru: "Привет! Я твой коуч. Как пройдёт наше занятие — зависит от тебя. Не бойся ошибок, я здесь чтобы помочь! 💪", en: "Hi! I'm your coach. How our session goes depends on you. Don't be afraid of mistakes — I'm here to help! 💪" },
  "chat.coachPersonality": { ru: "Ваш коуч", en: "Your Coach" },
  "chat.coachFriendly": { ru: "Дружелюбный", en: "Friendly" },
  "chat.coachStrict": { ru: "Строгий", en: "Strict" },
  "chat.coachCalm": { ru: "Спокойный", en: "Calm" },
  "chat.coachHumorous": { ru: "Весёлый", en: "Humorous" },
  "chat.coachPatient": { ru: "Терпеливый", en: "Patient" },
  "chat.coachMotivating": { ru: "Мотивирующий", en: "Motivating" },
  "chat.coachProfessional": { ru: "Профессиональный", en: "Professional" },
  "chat.coachCasual": { ru: "Непринуждённый", en: "Casual" },
  "chat.pin": { ru: "Закрепить", en: "Pin" },
  "chat.unpin": { ru: "Открепить", en: "Unpin" },
  "chat.editSettings": { ru: "Настройки чата", en: "Chat settings" },
  "chat.vocabMode": { ru: "Словарь", en: "Vocabulary" },
  "chat.voiceMode": { ru: "Голос", en: "Voice" },
  "chat.rename": { ru: "Переименовать", en: "Rename" },
  "chat.delete": { ru: "Удалить", en: "Delete" },
  "chat.renameTitle": { ru: "Переименовать чат", en: "Rename chat" },
  "chat.renamePlaceholder": { ru: "Название чата", en: "Chat name" },
  "chat.deleteTitle": { ru: "Удалить чат?", en: "Delete chat?" },
  "chat.deleteDesc": { ru: "История диалога будет удалена безвозвратно.", en: "The conversation history will be permanently deleted." },

  "time.justNow": { ru: "сейчас", en: "just now" },
  "time.minAgo": { ru: "мин назад", en: "min ago" },
  "time.hoursAgo": { ru: "ч назад", en: "h ago" },
  "time.daysAgo": { ru: "дн назад", en: "days ago" },

  // Audio Conversation
  "audio.title": { ru: "Аудиоразговор", en: "Audio Conversation" },
  "audio.subtitle": { ru: "Говорите вслух — ИИ слушает и отвечает голосом", en: "Speak aloud — AI listens and responds with voice" },
  "audio.tapToTalk": { ru: "Зажмите и говорите", en: "Hold to talk" },
  "audio.clickToStart": { ru: "Нажмите — начать запись", en: "Click to start recording" },
  "audio.clickToStop": { ru: "Нажмите — закончить запись", en: "Click to stop recording" },
  "audio.listening": { ru: "Слушаю...", en: "Listening..." },
  "audio.speaking": { ru: "Говорю...", en: "Speaking..." },
  "audio.processing": { ru: "Обрабатываю...", en: "Processing..." },
  "audio.errorNoSpeech": { ru: "Речь не распознана. Попробуйте снова.", en: "Speech not recognized. Try again." },
  "audio.errorNoMic": { ru: "Микрофон недоступен. Проверьте разрешения.", en: "Microphone not available. Check permissions." },
  "audio.loginRequired": { ru: "Войдите в аккаунт, чтобы использовать аудиоразговор.", en: "Sign in to use audio conversation." },
  "audio.browserUnsupported": { ru: "Распознавание речи работает в Chrome и Edge.", en: "Speech recognition works in Chrome and Edge." },
  "audio.startSession": { ru: "Начать сессию", en: "Start session" },
  "audio.selectCoach": { ru: "Тип коуча", en: "Coach type" },
  "audio.you": { ru: "Вы", en: "You" },
  "audio.explainLang": { ru: "Язык объяснений", en: "Explanation language" },
  "audio.explainLangDesc": { ru: "Объяснения ошибок и ответы на вопросы — на выбранном языке", en: "Error explanations and answers to questions — in the selected language" },
  "audio.subtitleHistory": { ru: "История субтитров", en: "Subtitle history" },
  "audio.hideSubtitles": { ru: "Скрыть субтитры", en: "Hide subtitles" },
  "audio.showSubtitles": { ru: "Показать субтитры", en: "Show subtitles" },
  "audio.loading": { ru: "Загрузка...", en: "Loading..." },
  "audio.noSubtitlesYet": { ru: "Здесь будут ваши реплики и ответы AI", en: "Your lines and AI responses will appear here" },

  // Listening (legacy)
  "listening.title": { ru: "Аудирование", en: "Listening Lab" },
  "listening.subtitle": { ru: "Слушайте, читайте субтитры и улучшайте понимание", en: "Listen, read subtitles, and improve comprehension" },
  "listening.hideTranslation": { ru: "Скрыть перевод", en: "Hide translation" },
  "listening.showTranslation": { ru: "Показать перевод", en: "Show translation" },

  // Settings
  "settings.title": { ru: "Настройки", en: "Settings" },
  "settings.subtitle": { ru: "Настройте обучение под себя", en: "Customize your learning experience" },
  "settings.general": { ru: "Основные", en: "General" },
  "settings.profile": { ru: "Профиль", en: "Profile" },
  "settings.data": { ru: "Данные", en: "Data" },
  "settings.account": { ru: "Аккаунт", en: "Account" },
  "settings.theme": { ru: "Тема", en: "Theme" },
  "settings.themeLight": { ru: "Светлая", en: "Light" },
  "settings.themeDark": { ru: "Тёмная", en: "Dark" },
  "settings.themeSystem": { ru: "Системная", en: "System" },
  "settings.name": { ru: "Имя", en: "Name" },
  "settings.dailyGoal": { ru: "Дневная цель (минуты)", en: "Daily goal (minutes)" },
  "settings.language": { ru: "Язык", en: "Language" },
  "settings.nativeLang": { ru: "Родной язык", en: "Native language" },
  "settings.preferences": { ru: "Настройки", en: "Preferences" },
  "settings.reminders": { ru: "Ежедневные напоминания", en: "Daily reminders" },
  "settings.remindersDesc": { ru: "Получать уведомления для практики", en: "Get notified to practice" },
  "settings.sound": { ru: "Звуковые эффекты", en: "Sound effects" },
  "settings.soundDesc": { ru: "Воспроизводить звуки при действиях", en: "Play sounds on actions" },
  "settings.darkMode": { ru: "Тёмная тема", en: "Dark mode" },
  "settings.darkModeDesc": { ru: "Использовать тёмную тему", en: "Use dark theme" },
  "settings.email": { ru: "Email", en: "Email" },
  "settings.security": { ru: "Безопасность и конфиденциальность", en: "Security & Privacy" },
  "settings.changePassword": { ru: "Сменить пароль", en: "Change password" },
  "settings.changePasswordDesc": { ru: "Обновите пароль для защиты аккаунта", en: "Update your password to keep your account secure" },
  "settings.currentPassword": { ru: "Текущий пароль", en: "Current password" },
  "settings.newPassword": { ru: "Новый пароль", en: "New password" },
  "settings.confirmPassword": { ru: "Подтвердите пароль", en: "Confirm password" },
  "settings.savePassword": { ru: "Сохранить пароль", en: "Save password" },
  "settings.error": { ru: "Ошибка", en: "Error" },
  "settings.enterCurrentPassword": { ru: "Введите текущий пароль", en: "Enter your current password" },
  "settings.passwordMinLength": { ru: "Пароль должен быть не менее 8 символов", en: "Password must be at least 8 characters" },
  "settings.passwordMismatch": { ru: "Пароли не совпадают", en: "Passwords do not match" },
  "settings.passwordChanged": { ru: "Пароль успешно изменён", en: "Password changed successfully" },
  "settings.logoutAll": { ru: "Выйти со всех устройств", en: "Log out of all devices" },
  "settings.logoutAllDesc": { ru: "Завершить все активные сессии", en: "End all active sessions" },
  "settings.logoutAllConfirmTitle": { ru: "Выйти со всех устройств?", en: "Log out of all devices?" },
  "settings.logoutAllConfirmDesc": { ru: "Все активные сессии будут завершены. Вам придётся войти заново.", en: "All active sessions will be terminated. You'll need to log in again." },
  "settings.loggedOutAll": { ru: "Вы вышли со всех устройств", en: "Logged out of all devices" },
  "settings.exportData": { ru: "Экспорт данных", en: "Export data" },
  "settings.exportDataDesc": { ru: "Скачать все ваши данные в формате JSON", en: "Download all your data as JSON" },
  "settings.dataExported": { ru: "Данные подготовлены к скачиванию", en: "Data ready for download" },
  "settings.dangerZone": { ru: "Опасная зона", en: "Danger Zone" },
  "settings.logout": { ru: "Выйти из аккаунта", en: "Log out" },
  "settings.logoutDesc": { ru: "Выйти из текущей сессии", en: "Sign out of your current session" },
  "settings.logoutConfirmTitle": { ru: "Выйти из аккаунта?", en: "Log out?" },
  "settings.logoutConfirmDesc": { ru: "Вы уверены, что хотите выйти?", en: "Are you sure you want to log out?" },
  "settings.loggedOut": { ru: "Вы вышли из аккаунта", en: "You have been logged out" },
  "settings.deleteAccount": { ru: "Удалить аккаунт", en: "Delete account" },
  "settings.deleteAccountDesc": { ru: "Навсегда удалить аккаунт и все данные", en: "Permanently delete your account and all data" },
  "settings.deleteConfirmTitle": { ru: "Удалить аккаунт навсегда?", en: "Delete account permanently?" },
  "settings.deleteConfirmDesc": { ru: "Это действие необратимо. Все ваши данные, прогресс и настройки будут удалены безвозвратно.", en: "This action cannot be undone. All your data, progress, and settings will be permanently deleted." },
  "settings.deleteForever": { ru: "Удалить навсегда", en: "Delete forever" },
  "settings.accountDeleted": { ru: "Аккаунт удалён", en: "Account deleted" },
  "settings.cancel": { ru: "Отмена", en: "Cancel" },
  "settings.confirm": { ru: "Подтвердить", en: "Confirm" },

  // Grammar
  "grammar.title": { ru: "Грамматика", en: "Grammar Quest" },
  "grammar.subtitle": { ru: "Проверьте свои знания грамматики", en: "Test your grammar knowledge" },
  "grammar.next": { ru: "Далее", en: "Next" },
  "grammar.finish": { ru: "Завершить", en: "Finish" },
  "grammar.complete": { ru: "Квест завершён!", en: "Quest Complete!" },
  "grammar.score": { ru: "Ваш результат", en: "You scored" },
  "grammar.tryAgain": { ru: "Попробовать снова", en: "Try Again" },

  // Pronunciation
  "pronunciation.title": { ru: "Произношение", en: "Pronunciation" },
  "pronunciation.subtitle": { ru: "Слушайте, повторяйте и совершенствуйте акцент", en: "Listen, repeat, and perfect your accent" },
  "pronunciation.listening": { ru: "Слушаю...", en: "Listening..." },
  "pronunciation.attempts": { ru: "попыток записано", en: "attempt(s) recorded" },

  // Writing
  "writing.title": { ru: "Письменный наставник", en: "Writing Mentor" },
  "writing.subtitle": { ru: "Практикуйте письмо с обратной связью от ИИ", en: "Practice writing with AI-powered feedback" },
  "writing.placeholder": { ru: "Начните писать здесь...", en: "Start writing here..." },
  "writing.words": { ru: "слов", en: "words" },
  "writing.getFeedback": { ru: "Получить отзыв", en: "Get Feedback" },
  "writing.aiFeedback": { ru: "Отзыв ИИ", en: "AI Feedback" },

  // Not found
  "notFound.title": { ru: "Страница не найдена", en: "Oops! Page not found" },
  "notFound.back": { ru: "Вернуться на главную", en: "Return to Home" },

  // Skill Map
  "skills.title": { ru: "Карта навыков", en: "Skill Map" },
  "skills.subtitle": { ru: "Отслеживайте прогресс по каждому навыку", en: "Track your progress across every skill" },
  "skills.overallLevel": { ru: "Общий уровень CEFR", en: "Overall CEFR Level" },
  "skills.avgLevel": { ru: "Средний уровень", en: "Avg level" },
  "skills.yourSkills": { ru: "Ваши навыки", en: "Your Skills" },
  "skills.vocabulary": { ru: "Словарный запас", en: "Vocabulary" },
  "skills.grammar": { ru: "Грамматика", en: "Grammar" },
  "skills.fluency": { ru: "Беглость речи", en: "Fluency" },
  "skills.listening": { ru: "Аудирование", en: "Listening" },
  "skills.pronunciation": { ru: "Произношение", en: "Pronunciation" },
  "skills.writing": { ru: "Письмо", en: "Writing" },
  "skills.lvl": { ru: "Ур.", en: "Lvl" },
  "skills.easiestGoal": { ru: "⚡ Ближайшая цель", en: "⚡ Easiest goal" },
  "skills.tipTitle": { ru: "Совет дня", en: "Tip of the day" },
  "skills.tipDesc": { ru: "Сфокусируйтесь на навыке с отметкой «Ближайшая цель» — он ближе всего к повышению уровня. Маленькие победы мотивируют продолжать!", en: "Focus on the skill marked 'Easiest goal' — it's closest to leveling up. Small wins keep you motivated!" },

  // Subscription
  "sub.title": { ru: "Выберите план", en: "Choose your plan" },
  "sub.subtitle": { ru: "Учите языки быстрее с расширенными возможностями", en: "Learn languages faster with advanced features" },
  "sub.backToSettings": { ru: "Назад в настройки", en: "Back to Settings" },
  "sub.monthly": { ru: "Ежемесячно", en: "Monthly" },
  "sub.yearly": { ru: "Ежегодно", en: "Yearly" },
  "sub.perMonth": { ru: "/ мес", en: "/ mo" },
  "sub.perYear": { ru: "/ год", en: "/ yr" },
  "sub.forever": { ru: "навсегда", en: "forever" },
  "sub.popular": { ru: "Популярный", en: "Popular" },
  "sub.currentPlan": { ru: "Текущий план", en: "Current plan" },
  "sub.upgrade": { ru: "Оформить", en: "Upgrade" },
  "sub.subscribed": { ru: "Вы подписались на план", en: "Subscribed to plan" },
  "sub.freeName": { ru: "Бесплатный", en: "Free" },
  "sub.freeDesc": { ru: "Базовые функции для начала обучения", en: "Basic features to start learning" },
  "sub.freeFeat1": { ru: "3 диалога в день", en: "3 conversations / day" },
  "sub.freeFeat2": { ru: "Базовый словарь (500 слов)", en: "Basic vocabulary (500 words)" },
  "sub.freeFeat3": { ru: "Грамматические квесты", en: "Grammar quests" },
  "sub.freeFeat4": { ru: "Карта навыков", en: "Skill map" },
  "sub.proName": { ru: "Pro", en: "Pro" },
  "sub.proDesc": { ru: "Для серьёзной практики каждый день", en: "For serious daily practice" },
  "sub.proFeat1": { ru: "Безлимитные диалоги", en: "Unlimited conversations" },
  "sub.proFeat2": { ru: "Полный словарь (5 000+ слов)", en: "Full vocabulary (5,000+ words)" },
  "sub.proFeat3": { ru: "Аудирование с видео", en: "Listening with videos" },
  "sub.proFeat4": { ru: "Проверка произношения", en: "Pronunciation check" },
  "sub.proFeat5": { ru: "Детальная статистика", en: "Detailed statistics" },
  "sub.premiumName": { ru: "Premium", en: "Premium" },
  "sub.premiumDesc": { ru: "Максимум возможностей для быстрого прогресса", en: "Maximum features for fast progress" },
  "sub.premiumFeat1": { ru: "Всё из Pro", en: "Everything in Pro" },
  "sub.premiumFeat2": { ru: "ИИ-наставник по письму", en: "AI writing mentor" },
  "sub.premiumFeat3": { ru: "Персональный план обучения", en: "Personal learning plan" },
  "sub.premiumFeat4": { ru: "Приоритетная поддержка", en: "Priority support" },
  "sub.premiumFeat5": { ru: "Экспорт прогресса", en: "Progress export" },
  "sub.premiumFeat6": { ru: "Ранний доступ к новинкам", en: "Early access to new features" },
  "settings.subscription": { ru: "Подписка", en: "Subscription" },
  "settings.subscriptionDesc": { ru: "Управляйте планом и оплатой", en: "Manage your plan and billing" },
  "settings.currentPlan": { ru: "Текущий план: Бесплатный", en: "Current plan: Free" },
} as const;

type TranslationKey = keyof typeof t;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  tr: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ru",
  setLang: () => {},
  tr: (key) => t[key]?.ru || key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("lingua-lang");
    return (saved === "en" || saved === "ru") ? saved : "ru";
  });

  const changeLang = (newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem("lingua-lang", newLang);
  };

  const tr = (key: TranslationKey) => t[key]?.[lang] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, tr }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
